# -*- coding: utf-8 -*-
"""English display text for «Elementos a verificar», «Anclas verificables»
and «Rúbrica — No aplica». Display only; the Spanish stays authoritative."""

ELEMENTOS = {
"1.1.1": "A. Explicit citation of P&B priorities / ILO outcomes.\nB. Explicit citation of the country's DWCP outcomes.\nC. Identifies at least one relevant CPO by code or name.\nD. Explains HOW the intervention contributes to A/B/C (not merely a list).",
"1.1.2": "A. Identifies the disability label/marker of the CPOs referenced.\nB. The proposal presents DEDICATED disability actions (not merely a mention).\nC. The level (visibility and ambition) matches the CPO label.",
"1.1.3": "A. Identifies the CPO gender marker (0/1/2/3 or equivalent).\nB. The proposal presents DEDICATED gender actions.\nC. The level matches the CPO marker.",
"1.2.1": "A. Identifies the current national development plan (by name).\nB. Identifies the UN cooperation framework (UNSDCF/equivalent).\nC. Articulates how the project fits within A and B.",
"1.2.2": "A. Identifies the UNSDCF outcomes/areas to which it contributes.\nB. Identifies the areas where the ILO is the responsible or convening agency.\nC. Articulates the project's contribution to A and B.",
"1.2.3": "A. Identifies SDG indicators by code (e.g. 8.5.2, 1.3.1).\nB. Those indicators correspond to the SDGs already linked to the CPOs.\nC. The SDG indicators appear in the logical framework or the M&E plan.",
"1.3.1": "A. There is a section or annex devoted to the situation analysis.\nB. The analysis cites sources (studies, official data, evaluations, consultations).\nC. The problem is bounded in scope, magnitude and affected population.",
"1.3.2": "A. It distinguishes immediate, underlying and structural causes (or an equivalent scheme).\nB. The causes are linked to evidence or consultation.\nC. The project strategy relates to causes, not only to symptoms.",
"1.3.3": "A. Identifies the affected population group by name and magnitude.\nB. Gender analysis of the context (covering at least one of: roles, sexual division of labour, opportunities and constraints differentiated by sex).\nC. Sex-disaggregated data where available.",
"1.3.4": "A. Stakeholder mapping (institutional, social, beneficiaries).\nB. Constraints and interests of each relevant actor.\nC. Explicit inclusion of women's organizations.\nD. Explicit inclusion of organizations of persons with disabilities where the project affects them.\nE. Analysis of power/influence among actors.",
"1.3.5": "A. Documented consultation plan with a methodology.\nB. Specific inclusion of marginalised groups (not merely a list).\nC. Measures for equitable participation (accessibility, translation, scheduling).\nD. Analysis of potential discriminatory effects and their mitigation.\nE. Free, prior and informed consent for indigenous peoples where applicable (FPIC).",
"1.4.1": "A. Explicit reference to the ILO's normative identity (conventions, recommendations).\nB. Explicit reference to tripartism (constituents: government, employers, workers).\nC. A value-added argument specific to the project (not generic).",
"1.4.2": "A. Description of the ILO's presence in the country (office, team).\nB. List or summary of relevant past/ongoing projects.",
"1.4.3": "A. Cites specific evaluations (project, country programme, strategy).\nB. (Optional) Draws out concrete lessons learned.\nC. Links those lessons to design decisions in the present project.",
"1.5.1": "A. Sub-objective, outcome or output whose title names disability.\nB. Indicator disaggregated by disability or measuring it specifically.\nC. Activity whose main purpose is disability.\nD. (Optional, depending on the nature of the project) Budget line for disability.\nE. (Optional, depending on the nature of the project) Quantifiable target relating to disability.",
"1.5.2": "A. Cites conventions/recommendations by number (e.g. C111, C190).\nB. Those instruments are integrated into the strategy (not merely listed).\nC. Indicators or objectives link to those instruments.\nD. Actions promoting ratification/application/awareness.\nE. References to NORMLEX or other legal sources.",
"1.5.3": "A. Cites CEACR observations/direct requests concerning the country.\nB. Cites conclusions of the Committee on the Application of Standards or the Committee on Freedom of Association where applicable.\nC. Those observations inform the project's justification or strategy (an explicit link, not decorative).",
"1.5.4": "A. Explicit commitment to ILS compliance within the project.\nB. Fair wages specified (legal or sectoral reference).\nC. OSH conditions applicable to project staff and contractors.\nD. Grievance mechanism accessible to workers.\nE. Compliance clauses in third-party contracts.",
"1.5.5": "A. Analysis of the project's potential environmental impacts.\nB. Measures to mitigate the impacts identified.\nC. Consideration of biodiversity and affected communities.\nD. Sustainable practices in implementation (materials, energy, waste).\nE. Where there is infrastructure/construction: specific environmental safety measures.",
"1.5.6": "A. Distinguishes gender-sensitive / responsive / transformative approaches.\nB. Explicitly articulates how the project challenges gender norms or power relations.\nC. DEDICATED actions to transform relations (not merely to include women).\nD. Indicators measure changes in relations, not only numerical participation.\nE. Cites technical guidance (e.g. \"Practical Guide\" No. 15).",
"2.1.1": "A. Describes the consultation/participation process during design (what, when, with whom).\nB. Lists the constituents consulted (government, employers, workers).\nC. Defines the parties' role in monitoring.\nD. Defines the parties' role in implementation.",
"2.1.2": "A. Key stakeholders identified by name.\nB. Each stakeholder's link to the final beneficiaries.\nC. Role in relation to the problem (cause, affected, mitigator).\nD. Role in relation to the solution (implementer, validator, beneficiary).",
"2.1.3": "A. Explicit mention of consultation with ACT/EMP.\nB. Explicit mention of consultation with ACTRAV.\nC. The outcome of the consultation is integrated into the design.",
"2.2.1": "A. Describes the consultations held (when, with whom, on what).\nB. Lists concrete commitments made by partners.\nC. (Optional) Those commitments are operational (time, resources, decisions) — not merely declaratory.",
"2.2.2": "A. Evidence of acceptance of the objectives by each key partner.\nB. Acceptance of the performance framework / indicators.\nC. Acceptance of obligations and responsibilities.",
"2.2.3": "A. Explicit strategy for continuous ownership (not merely one-off events).\nB. Shared governance mechanisms (committees, steering groups).\nC. Link to the sustainability strategy.",
"2.3.1": "A. Capacity assessment carried out OR planned, with a methodology.\nB. Explicit conclusions (existing capacities vs gaps).\nC. Those conclusions inform the project design.",
"2.3.2": "A. Individual (technical) capacities.\nB. Organizational capacities (systems, processes).\nC. Enabling environment (legal framework, policies, financing).",
"2.4.1": "A. Evidence of explicit constituent interest in the post-project period.\nB. That evidence is concrete (letter, MoU, allocation of future staff/budget).",
"2.4.2": "A. Institutional mechanism (training of trainers, integration into existing systems).\nB. Financial mechanism (post-project funding sources).\nC. Governance mechanism (who sustains the results).\nD. Transition timetable.",
"2.4.3": "A. The proposal identifies the preconditions for scaling up.\nB. Defines objective success criteria.\nC. Plan for measuring/demonstrating success.\nD. Plan for transition to the scale-up phase.",
"2.4.4": "A. Identifies the source of human resources after the project.\nB. Identifies the source of financial resources after the project.\nC. Argues plausibility (not merely declaratory).",
"2.4.5": "A. Explicit exit strategy.\nB. Plan for transferring responsibilities (what, to whom, when).\nC. Capacity development actions specific to the transfer.\nD. Exit timetable.",
"3.1.1": "A. The outputs → outcomes → impact causal chain is made explicit.\nB. Mechanisms of change identified (not merely arrows).\nC. Critical assumptions stated.\nD. Discursive emphasis on results (not on a list of activities).",
"3.1.2": "A. Coverage: the outputs cover the outcomes with no logical gaps.\nB. Sufficiency: each outcome has outputs that justify achieving it.\nC. The outcomes → impact link is reasoned.",
"3.1.3": "A. Specific actors of capacity development are named.\nB. Type of change expected (performance, behaviour, practices).\nC. Mechanism by which capacity translates into change.",
"3.1.4": "A. Assumptions stated explicitly.\nB. Assumptions tied to levels of the chain (outputs / outcomes / impact).\nC. Reference to past or parallel interventions (ILO or other actors).",
"3.1.5": "A. Cites specific evaluations (project, programme, study).\nB. Those evaluations support causal links in the logical framework.\nC. The lessons are explicitly applied to the present design.",
"3.2.1": "A. Outcome statements express states/situations (X is strengthened, Y has access).\nB. Absence of activity formulations (\"through\", \"by means of\", \"by carrying out\").",
"3.2.2": "S — Specific (what exactly).\nM — Measurable (with what indicator and threshold).\nA — Achievable (feasible with the resources).\nR — Relevant (linked to the problem and the ToC).\nT — Time-bound (with a defined deadline).",
"3.2.3": "A. Outputs framed as deliverables (\"Document X published\", \"N people certified\").\nB. Absence of activity formulations (\"Hold workshops\", \"Train…\").",
"3.3.1": "A. Outcome or output whose title names gender/equality/women.\nB. Indicator disaggregated by sex or gender-specific.\nC. Quantifiable target by sex or on gender.",
"3.3.2": "A. Outcome or output that names disability.\nB. Disability-specific or disaggregated indicator.\nC. Quantifiable disability target.",
"3.4.1": "A. There is a risk analysis section or annex.\nB. The risks are categorised (strategic, operational, fiduciary, contextual).",
"3.4.2": "A. SEA-specific risks identified.\nB. Prevention mechanisms (codes of conduct, mandatory training).\nC. Accessible and confidential reporting mechanism.\nD. Response protocol and victim support.\nE. SEA clauses in third-party contracts.",
"3.4.3": "A. Identification of community risks (not only risks to project staff; not cross-cutting).\nB. Measures for physical and environmental risks (traffic, hazardous materials, pollution; cross-cutting component: Environment).\nC. Where there is security personnel: use-of-force and abuse-prevention protocol (conditional; not cross-cutting).\nD. Community grievance mechanism (not cross-cutting).\nNote: apply DEDICATED vs FRAMING only to the environmental evidence. Do not treat community risks, OSH or security as cross-cutting themes.",
"3.4.4": "A. Identifies ILS non-compliance risks in the project context.\nB. Links to CEACR observations or other supervisory bodies.\nC. Specific mitigation plan.",
"3.4.5": "A. Risk register in the current ILO format.\nB. Attached to the proposal (as an annex, not merely referenced).",
"3.4.6": "A. Specificity: each risk is contextual to the project, not a generic template.\nB. Likelihood and impact rated.\nC. Risks material to the project's success.",
"3.4.7": "A. Each medium/high risk has a mitigation measure.\nB. Each measure has an owner.\nC. Each measure has a monitoring method.",
"3.5.1": "A. Collection system described (what data, how often, by whom).\nB. Justification of the resources allocated to M&E.\nC. Evaluability review where applicable (project above the threshold).\nD. (Optional) Project learning plan.",
"3.5.2": "A. Feedback loop defined (data → decisions).\nB. Information needs for reporting specified.\nC. Responsible staff named or identified by post.\nD. Frequency of the review cycles.",
"3.5.3": "A. M&E plan as a discrete document or section.\nB. Collection methods named (survey, interview, administrative records).\nC. Analysis methods specified.\nD. Roles and responsibilities per method/indicator.",
"3.5.4": "A. SMART indicators (all five attributes).\nB. Gender-sensitive (sex-disaggregated or gender-specific).\nC. Allow for disability inclusion (disaggregated or specific).\nD. Baseline for each indicator.\nE. Target and milestones defined.\nF. Coverage of the outcomes (not only outputs).",
"3.5.5": "A. Separate evaluation budget line.\nB. Amount ≥ ~2% of the total budget (or a justification if it differs).",
"3.6.1": "A. Where there is an inception phase: activities and results of the initial period made explicit.\nB. Overall timeframe justified against complexity and capacities.\nC. Timetable with quarterly or half-yearly milestones.",
"3.6.2": "A. Budget broken down by activity or output.\nB. Consistency between logical framework activities and budget lines.\nC. (Optional) Unit costs or calculations visible.",
"3.6.3": "A. Budget line for a gender specialist where applicable.\nB. Budget line for a disability specialist where applicable.\nC. Budget line for information accessibility (plain language, alternative formats).\nD. Budget line for interpretation into local languages or sign language where applicable.",
"3.7.1": "A. Explicit mention of cost-effectiveness or \"value for money\".\nB. Linked to the design (not only to administration).",
"3.7.2": "A. Analysis of design alternatives with costs/benefits.\nB. Justification of the option chosen.\nC. Where applicable: comparison against benchmarks (similar projects).",
"4.1.1": "A. Identifies the managing office/unit.\nB. Where management is regional/national: a field office close to the beneficiaries.\nC. Where management is centralised: explicit justification on effectiveness grounds.",
"4.1.2": "A. Organigram or description of staff roles.\nB. Explicit line of accountability (who reports to whom).\nC. Responsible ILO official identified by post or name.",
"4.1.3": "A. Identifies the technical or administrative units that will provide support.\nB. That support is budgeted for (a line or allocation).",
"4.1.4": "A. Staffing plan.\nB. Procurement procedures (ILO standards or adaptations).\nC. Financial and reporting systems.\nD. Levels of authority and approval.",
"4.1.5": "A. Decent work clauses in third-party contracts.\nB. Fair employment clauses (wages, working time, freedom of association).\nC. Grievance mechanism accessible to third-party workers.\nD. Compliance monitoring by the ILO.",
"4.2.1": "A. Roles of each institution/partner made explicit.\nB. Implementation procedures (how they work together).\nC. Justification for the choice of partners (why these and not others).",
"4.2.2": "A. Explicit evidence of acceptance by each partner.\nB. Supporting document (letter, MoU, minutes).",
"4.2.3": "A. Organizational capacity assessment carried out or planned.\nB. Explicit reference in the proposal (not only in an uncited annex).",
"4.2.4": "A. Capacity development plan for the implementing partners.\nB. Operational components (training, mentoring, accompaniment).\nC. Gender-responsiveness component.",
"4.2.5": "A. Partners' track record (similar projects, demonstrated capacity).\nB. Plausibility argument (not merely \"they are competent\").\nC. Mitigation where demonstrated capacity is limited.",
"4.3.1": "A. Stakeholder communication plan (what, when, how).\nB. Expected communication products (reports, briefings, events).\nC. Human resources allocated.\nD. Financial resources allocated.",
"4.4.1": "A. Public communication strategy (not only a technical one).\nB. Development timetable where the strategy is not yet drafted.\nC. Expected products (press notes, social media, multimedia).",
"4.4.2": "A. Human resources allocated to communication.\nB. Financial resources allocated.\nC. Formats accessible to persons with disabilities.\nD. Products in local languages / plain language / sign language where applicable.",
"4.4.3": "A. DCOMM template completed.\nB. Coordination with the relevant country office.",
"5.1.1": "A. All sections of the ILO template present.\nB. Order consistent with the guidance.\nC. Required annexes included.",
"5.2.1": "A. Core ideas identifiable without re-reading.\nB. Absence of unnecessary jargon or repetition.\nC. Visible structure (subheadings, tables, bullets where they help).",
}

# Anclas: son pistas de BÚSQUEDA, no reglas de decisión. En inglés se dan los
# equivalentes ingleses, conservando códigos, regex, URLs y siglas.
ANCLAS = {
"1.1.1": "P&B; DWCP; CPO; \"contributes to\", \"aligns with\", \"feeds into\"; CPO codes (e.g. ABC-101)",
"1.1.2": "\"disability label\"; \"disability marker\"; \"disability principal/significant/limited\"; CPO names with their marker",
"1.1.3": "\"gender marker\"; \"GEM\"; \"principal/significant/limited\"; CPO code with marker",
"1.2.1": "\"UNSDCF\"; \"UNDAF\"; official name of the national plan; \"National Development Plan\"; \"National Strategy\"",
"1.2.2": "\"UNSDCF Outcome\", \"UNSDCF Outcome X\", \"ILO leads\", \"ILO convenes\"",
"1.2.3": "regex pattern \\d+\\.\\d+\\.\\d+ ; \"SDG indicator\"; \"SDG marker\"",
"1.3.1": "\"situation analysis\"; \"problem statement\"; bibliographic citations; figures with %, USD or N=",
"1.3.2": "\"immediate/underlying/structural causes\"; \"problem tree\"; \"root of the problem\"",
"1.3.3": "\"gender analysis\"; \"gender roles\"; \"sexual division of labour\"; data broken down \"women/men\" or \"F/M\"",
"1.3.4": "\"stakeholder mapping\"; \"stakeholder analysis\"; names of OPDs, women's organizations",
"1.3.5": "\"FPIC\"; \"free, prior and informed consent\"; \"interpretation\"; \"accessible language\"; names of marginalised groups",
"1.4.1": "\"normative\", \"tripartite\", \"employers and workers\", \"ILO constituents\"; conventions cited by number",
"1.4.2": "\"ILO Office in\"; names of past projects; project codes",
"1.4.3": "\"evaluation of\", \"lessons learned\"; years; ievaldiscovery URLs",
"1.5.1": "\"persons with disabilities\"; \"PwD\"; \"accessibility\"; \"disaggregated by disability\"",
"1.5.2": "\"C087\", \"C098\", \"C190\"; \"Convention No.\"; \"NORMLEX\"; normlex.ilo.org URL",
"1.5.3": "\"CEACR\"; \"Committee of Experts\"; \"Committee on Freedom of Association\"; \"Committee on the Application of Standards\"",
"1.5.4": "\"wages\", \"OSH\", \"occupational safety and health\", \"grievance mechanism\", \"code of conduct\"",
"1.5.5": "\"environmental impact\"; \"biodiversity\"; \"waste\"; \"energy\"; \"environmental sustainability\"",
"1.5.6": "\"transformative approach\", \"power relations\", \"gender norms\", \"Practical Guide No. 15\"",
"2.1.1": "names of ministries; trade union confederations; employers' chambers; \"in monitoring\", \"in implementation\"",
"2.1.2": "stakeholder table; columns \"role\", \"interest\", \"link\"",
"2.1.3": "\"ACT/EMP\"; \"ACTRAV\"; \"specialists consulted\"; specific names",
"2.2.1": "\"minutes of meeting\", \"MoU\", \"letter of intent\"; consultation dates",
"2.2.2": "\"MoU\", \"letter of intent\", \"cooperation agreement\"; references to annexes",
"2.2.3": "\"steering committee\", \"coordination group\"",
"2.3.1": "\"capacity assessment\", \"gap analysis\"",
"2.3.2": "\"individual / organizational capacities / enabling environment\"; \"systemic\"; \"policy\"",
"2.4.1": "\"post-project\", \"sustainability\", letters of commitment, future budget allocations",
"2.4.2": "\"sustainability plan\"; \"sustaining results\"",
"2.4.3": "\"pilot\", \"test phase\", \"proof of concept\", \"scale-up\"",
"2.4.4": "\"post-project resources\", \"sectoral budget\", \"budget line\"",
"2.4.5": "\"exit strategy\", \"transfer of responsibilities\"",
"3.1.1": "\"theory of change\", \"ToC\", \"mechanism of change\", \"critical assumption\", \"if X then Y\"",
"3.1.2": "\"logical framework\", \"logframe\"; verbs connecting rows",
"3.1.3": "\"behavioural change\", \"improved performance\", \"practical application\"",
"3.1.4": "\"assumption\", \"it is assumed\", \"precondition\"",
"3.1.5": "\"evaluation\", \"meta-evaluation\", \"ievaldiscovery\", evaluation years",
"3.2.1": "\"is strengthened\", \"has access\", \"has been improved\"; absence of \"through\", \"by means of\"",
"3.2.2": "indicators with a figure/%, deadlines \"by 2026\", \"by the end of the project\"",
"3.2.3": "\"published\", \"certified\", \"delivered\"; absence of \"carry out\", \"undertake\"",
"3.3.1": "\"gender equality\", \"sex-disaggregated\", \"GEM\"; outcome titles naming gender",
"3.3.2": "\"disability inclusion\", \"disaggregated by disability\", \"PwD\"",
"3.4.1": "\"risk matrix\", \"risk analysis\", categories (\"operational\", \"fiduciary\")",
"3.4.2": "\"SEA\", \"sexual exploitation and abuse\", \"PSEA\", \"code of conduct\", \"reporting mechanism\"",
"3.4.3": "\"community health and safety\", \"community risks\", \"pollution\", \"hazardous materials\", \"community grievance mechanism\"",
"3.4.4": "\"non-compliance\", \"compliance risks\", \"CEACR\", conventions by number",
"3.4.5": "\"risk register\", total budget in USD",
"3.4.6": "\"high/medium/low likelihood\", \"impact\", \"1–5 scale\"",
"3.4.7": "columns \"measure\", \"owner\", \"monitoring\" in the risk matrix",
"3.5.1": "\"M&E system\", \"evaluability\", \"learning plan\", \"MEL\"",
"3.5.2": "\"feedback loop\", \"quarterly review\", \"half-yearly report\"",
"3.5.3": "\"collection method\", \"qualitative/quantitative analysis\", \"roles\"",
"3.5.4": "\"SMART\", \"disaggregated by sex / disability\", \"baseline\", \"target\", \"milestone\"",
"3.5.5": "\"evaluation budget\", \"evaluation line\", percentage of the total",
"3.6.1": "\"inception\", \"initial phase\", \"timetable\", \"Gantt\", \"quarterly milestones\"",
"3.6.2": "\"breakdown by activity\", \"BoQ\", \"cost driver\", \"unit cost\"",
"3.6.3": "\"gender/disability specialist\", \"accessibility\", \"local language\", \"sign language\"",
"3.7.1": "\"cost-effectiveness\", \"value for money\", \"efficiency\"",
"3.7.2": "\"analysis of alternatives\", \"benchmark\", \"cost-benefit\"",
"4.1.1": "\"field office\", \"headquarters\", \"decentralised\", \"justification for centralisation\"",
"4.1.2": "\"organigram\", \"reports to\", \"responsible ILO official\", specific names/posts",
"4.1.3": "\"backstopping\", \"technical unit\", \"administrative support\", unit names (PROGRAM, ENTERPRISES, …)",
"4.1.4": "\"procurement\", \"IRIS\", \"levels of authority\"",
"4.1.5": "\"contractor\", \"subcontractor\", \"decent work clause\", \"grievance mechanism\"",
"4.2.1": "\"selection of partners\", \"selection criteria\", \"modus operandi\"",
"4.2.2": "\"letter of acceptance\", \"signed MoU\", \"agreed minutes\"",
"4.2.3": "\"organizational capacity assessment\", \"OCA\", \"institutional assessment\"",
"4.2.4": "\"institutional strengthening plan\", \"capacity development plan\", \"gender-responsive\"",
"4.2.5": "\"track record\", \"previous projects\", \"demonstrated capacity\"",
"4.3.1": "\"communication plan\", \"briefing\", \"quarterly report\"",
"4.4.1": "\"communication strategy\", \"general public\", \"human interest\"",
"4.4.2": "\"accessibility\", \"alternative formats\", \"sign language\", \"local language\"",
"4.4.3": "\"PPP\", \"public-private partnership\", \"European Commission\", \"DCOMM\", budget in USD",
"5.1.1": "\"Executive summary\", \"Background\", \"Logical framework\", \"Budget\", \"Annexes\" — compare against the ILO template",
"5.2.1": "executive summary, subheadings, paragraph length, tables vs prose",
}

NO_APLICA = {
"1.1.2": "Only if the CPOs explicitly referenced carry no disability label — this must be documented.",
"1.3.5": "E applies only if the project affects indigenous peoples — this must be documented.",
"1.5.1": "Document where the project explicitly justifies that disability does not apply.",
"1.5.3": "Document where the project has no link to ILS.",
"1.5.4": "If the project engages no workers directly or indirectly, document why this does not apply.",
"1.5.5": "If the project is 100% normative/advisory with no physical activities, document it but still assess A.",
"1.5.6": "If the context does not allow a transformative approach, this must be explicitly justified.",
"2.4.3": "DECISION: ¬T1 (no test phase is defined) → explicit N/A",
"3.3.1": "Only if the CPO gender marker is 0 — this must be documented.",
"3.3.2": "Only if the CPO disability label does not apply — this must be documented.",
"3.4.3": "If the project is 100% remote/normative with no physical presence, document it.",
"3.4.5": "DECISION: ¬T1 (budget ≤ USD 1M)",
"3.5.1": "Document the threshold criterion for C.",
"3.6.1": "Document where there is no inception phase.",
"3.6.3": "Document item by item where it does not apply.",
"4.1.5": "DECISION: there are no contractors — document",
"4.2.4": "DECISION: the assessment identified no gaps — document",
"4.4.3": "DECISION: ¬T1   OR   ¬T2",
}

if __name__ == "__main__":
    import json
    import pathlib
    here = pathlib.Path(__file__).parent
    for name, data in (("elementos.json", ELEMENTOS), ("anclas.json", ANCLAS),
                       ("tests_na.json", NO_APLICA)):
        (here / name).write_text(
            json.dumps(data, ensure_ascii=False, indent=1), encoding="utf-8"
        )
        print(f"{len(data):3} entradas -> {name}")
